### ISSUE TITLE
Restructure the build system

### ISSUE THREAD

**Issue by pythonbrad** [Mindful/eei#12]
### Description
@Mindful, i like the fact that this project is using `rust` as main programing language.
Not like i was expected, the cmake command is not enough to build and install the project.
There is a script `./install.sh` but for a dev who want to customize the building, it's not enough. 

### Expected solution

```
cmake -B build . --install-prefix /usr
cmake --build build
sudo cmake --build build -t install
``` 

### Contribution
If you are ok, i would like to restructure the project using a modern Cmake approach.
And show you the benefit through a PR.

**Comment by Mindful** [comment]
@pythonbrad 

Hi there, thanks for opening an issue.

> Not like i was expected, the cmake command is not enough to build and install the project.
> There is a script ./install.sh but for a dev who want to customize the building, it's not enough.

To be clear, what you're saying is that the install script works but can't be customized at all, right?

> If you are ok, i would like to restructure the project using a modern Cmake approach.

Yeah, this would be great! I am very bad at Cmake - this is maybe the third Cmake file I've ever written - so I would welcome an overhaul of the Cmake stuff if you wanted to do that. The only thing is that please try and keep it relatively simple; I need to at least be able to understand it so that I can maintain it.

**Comment by Mindful** [comment]
Closed by https://github.com/Mindful/eei/pull/13

See PR link for more details.
