### ISSUE TITLE
Automate the autosuggestion

### ISSUE THREAD

**Issue by pythonbrad** [Mindful/eei#16]
### description 
Currently, to use the autosuggestion / autocompletion, we need to press ctrl+w or ctrl+e.
It will be great to automate it and the user will only have to select the desired suggestions.

**Comment by Mindful** [comment]
So, you could do this if you made it configurable somehow so that the user selected between the two modes of use. 
For what it's worth though, I originally had it like this - where the suggestions were just always on - and it felt kind of intrusive/awkward to me. It's also difficult to get this right when the user switches input targets; you know when a word is done if the user inputs a word, but if the user types "wa" in one window and then moves to another and starts typing, there's no way to know that you should clear that state.

**Comment by pythonbrad** [comment]
> It's also difficult to get this right when the user switches input targets; you know when a word is done if the user inputs a word, but if the user types "wa" in one window and then moves to another and starts typing

I think with the iBus API, we have [focus-in](https://lira.no-ip.org:8443/doc/ibus/html/IBusEngine.html#IBusEngine-focus-in) and [focus-out](https://lira.no-ip.org:8443/doc/ibus/html/IBusEngine.html#IBusEngine-focus-out) signals that can be used to detect if the user is doing something else than typing (change of input by example).

**Comment by Mindful** [comment]
So it's been a while since I did the original development, but I am pretty sure (although not 100% sure) that I tried to use these signals and found that the desktop environment I was using (Pop-OS) wasn't consistently sending them... or something like that.

That said, if you could get this working consistently/figure out what I did wrong, that would be a huge win. It would make it easier to do what you're talking about here, and also improve the current system too - because we actually still have the issue that I was talking about where you can switch windows and the character buffer isn't cleared.

**Comment by pythonbrad** [comment]
@Mindful 
There is a sample of implementation below.

From line 466 to 479.
https://github.com/ueno/ibus-skk/blob/master/src/engine.vala

When I will finish the implementation, I will let you know for your reviews. 👍

**Comment by Mindful** [comment]
So I just looked through the code and realized I'm actually using focus-out here: https://github.com/Mindful/eei/blob/main/src/predict/lib/src/lib.rs#L447

I'd be happy for you to work on the implementation, but I think the harder part here is understanding why/when this signal does (or doesn't) get sent, as opposed to just implementing it. I'm pretty sure the hard part for me was that it didn't get sent when I thought it would, but again I don't really remember.

**Comment by pythonbrad** [comment]
> So I just looked through the code and realized I'm actually using focus-out here: https://github.com/Mindful/eei/blob/main/src/predict/lib/src/lib.rs#L447

Alright, I will check it.

**Comment by pythonbrad** [comment]
> if the user types "wa" in one window and then moves to another and starts typing, there's no way to know that you should clear that state.

@Mindful , I will solve it in another issue

**Comment by pythonbrad** [comment]
@Mindful, after implemented a prototype, I think, the need of autosuggestion is on-demand and have it automatically is not useful.

**Illustration**

[demo](https://github.com/user-attachments/assets/31a8ffeb-28ac-47a3-9291-fb307d3f48cd)

**Comment by Mindful** [comment]
This is the same conclusion I came to after trying it, so I think we can close this 👍🏻
